### ISSUE TITLE
Question about PiSugar S Plus Shutdown

### ISSUE THREAD

**Issue by RevelRob** [PiSugar/PiSugar#100]
Hi. I have a PiSugar S Plus on a Raspberry Pi 3B. I am curious as to what the procedure is when power is cut to the battery. Does the battery discharge to a certain amount and then shut down the Raspberry Pi? If so, what does the battery discharge to? Also, is it a safe shutdown? or does it just cut the power to the Pi? Thanks very much!

**Comment by JdaieLin** [comment]
S version just cut the power under 3V, and restore until it's charged to 3.6v. There's no safe shutdown.
