### ISSUE TITLE
[Question] Does Pisugar 3 Plus support Raspberry Pi Zero 2W?

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [PiSugar/PiSugar#102]
Does Pisugar 3 Plus support Raspberry Pi Zero 2W? And if not what is the reason?

**Comment by Ra2-IFV** [comment]
It depends on which OS you use, I think.

**Comment by eqikkwkp25-cyber** [comment]
> It depends on which OS you use, I think.

@Ra2-IFV Do you have any reference or sources for this statement? And with which OS it works? My preferred OS is Raspian as for many others.

**Comment by Ra2-IFV** [comment]
> @Ra2-IFV Do you have any reference or sources for this statement? And with which OS it works? My preferred OS is Raspian as for many others.
> 
> My guess that the behavior is the same with a Pisugar 2 Pro 5000mah where the Pi Zeros are not listed as supported boards too.

Well, I think the only difference between Pi Sugar 3 Plus and Pi Sugar 3 is... They just made it bigger.
Since the GPIO pinouts of Rpi4 and Rpi Zero are TOTALLY the same, there is no reason why Pi Sugar 3 should not be compatible with Rpi Zero.

**Comment by Ra2-IFV** [comment]
Of course if your OS supports I2C, then it should support Pi Sugar

**Comment by eqikkwkp25-cyber** [comment]
In the meantime i own a PiSugar 2 Plus and it does not seem to work with a Pi Zero 2. See issues and comments within https://github.com/PiSugar/pisugar-power-manager-rs
