### ISSUE TITLE
[Pisugar3 Plus] Don't power on

### ISSUE THREAD

**Issue by amenekowo** [PiSugar/PiSugar#105]
I use my Pisugar3 with Rpi 4B and worked well until I left it for a few days. It suddenly don't power on after I press the power button. I can still link my RPI to the computer and access its i2c interface (the blue LED lights up), with a working hwclock. I tried update the bootloader, no errors but still don't work.
Any ideas?

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by shorage** [comment]
same

**Comment by amenekowo** [comment]
I got my unit replaced by contacting the seller on Taobao (AliExpress).
Btw the service is nice 🙂
