### ISSUE TITLE
Replace PiSugar 3 1200mAh battery with 4000mAh possible?

### ISSUE THREAD

**Issue by lh84** [PiSugar/PiSugar#106]
Hello together, 

is it possible to replace 1200mAh battery of PiSugar3 to a common other LiPo (4.000mah 3.7V / e.g. https://amzn.eu/d/5mG1oVo) battery? The 1200mAh accu lasts just 3 hours for my application and this is way to less for my use case. 

I am happy to get some answers. 

Cheers

**Comment by JdaieLin** [comment]
Hi, it should be ok to replace.
