### ISSUE TITLE
Wiki for config.json

### ISSUE THREAD

**Issue by leo150** [PiSugar/PiSugar#108]
Could you please add a wiki page about every field in `config.json`?
Somehow the settings don't always save automatically after changing them in Web UI (PiSugar 3)
I want to edit them manually but there's no docs about the fields

**Comment by JdaieLin** [comment]
@fengyc

**Comment by JdaieLin** [comment]
> Could you please add a wiki page about every field in `config.json`? Somehow the settings don't always save automatically after changing them in Web UI (PiSugar 3) I want to edit them manually but there's no docs about the fields

Please refer to https://github.com/PiSugar/pisugar-power-manager-rs/blob/master/doc/config.md
