### ISSUE TITLE
Pi Sugar 2 Pro Not Powering Raspi 4B???

### ISSUE THREAD

**Issue by NoobSquareplayz** [PiSugar/PiSugar#109]
I bought a pisugar 2 pro for my raspberry pi, i've powered it on and charged it to 100% battery and it still isnt powering the raspi 4? ive pressed the activate btn for 2 sec and the red light turns on the pi but none of the gpio pins work, and I cant see the raspi's ip on my network 
I<img width="949" alt="Screen Shot 2023-01-19 at 9 14 51 PM" src="https://user-images.githubusercontent.com/59814822/213622379-cb519774-111b-450b-9e77-5333f5de202b.png">

**Comment by JdaieLin** [comment]
Hi, does the pi works normally (also the network connect) when powered by its own type-c port?
