### ISSUE TITLE
PiSugar 3+ Inaccurate Voltage and SoC readings

### ISSUE THREAD

**Issue by SHONG0504** [PiSugar/PiSugar#110]
I am finding that there are discrepancies between the actual battery voltage and what is being detected by the PiSugar BMS.

When I measure the battery voltage with a multimeter, I am seeing a constant 4.0V, but when I'm reading the I2C registers 0x22 and 0x23 at the same time, I am getting wildly inaccurate readings between 3.2 and 3.6V.

I am on FW version 1.3.4, and using a RPi 4b.

This is affecting the PiSugar's ability to charge, as even after an overnight charge the SoC reads ~30% and quickly drops down to 20% within minutes, even though in reality it should be around 80% (charge protection on).

**Comment by wlmh110** [comment]
Hello, we will investigate this issue. Did you charge the PiSugar during the measurement process?
