### ISSUE TITLE
Mounting Problem with Pi4

### ISSUE THREAD

**Issue by tomschlde** [PiSugar/PiSugar#111]
Question:
I printed the case from the repo and tried to insert the completely assembled (Pisugar2 pro & RPI4) into the case - this did not work.
Is it correct that the assembly has to be done in 2 parts and that the PiSugar and the Rpi4 are first joined together inside the enclosure so that the clips on the side of the enclosure are pinched between the PCB of the RPi4 and the PiSugar?

TIA
Thomas

**Comment by JdaieLin** [comment]
Hi Thomas, it's correct as you described. The clips on the side of the enclosure are pinched between RPi4 and the PiSugar
