### ISSUE TITLE
RPI4B HyperPixel4 and PiSugar3Plus compatibility?

### ISSUE THREAD

**Issue by Gtjack9** [PiSugar/PiSugar#114]
What is the compatibility of the PiSugar3Plus on pi4B with a HyperPixel4 display installed?

Purportedly the HyperPixel4 uses all the GPIO headers that it is mounted on, does this prevent the communication between the PiSugar3Plus and the rpi4B?

is there any way to allow them to coexist or are they incompatible when installed together?

As soon as I installed the software for the PiSugar3Plus the hyperpixel4 stopped working on reboot.
I disabled I2c comms in Raspi-Config which allowed the display to work. But I still can’t access the power management server from the PiSugar.

**Comment by wlmh110** [comment]
Yes, based on the information we currently have, it seems that the HyperPixel4 uses the I2C interface exclusively, which prevents compatibility with the PiSugar3Plus.
We do not have a solution to make these two devices compatible.
