### ISSUE TITLE
[PiSugar 3] Change PiSugar 3 RTC i2c address

### ISSUE THREAD

**Issue by amenekowo** [PiSugar/PiSugar#117]
PiSugar 3 is amazing to include a rtc compatible with ds1307 driver. But I prefer to use a real DS3231SN module for higher time accuracy. Document says we can change PiSugar's mcu address. So if it's possible to alter the address of built-in rtc?
Any help appreciated ☺️

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by amenekowo** [comment]
Hi there!
Can we change i2c address or disable the rtc functionality now?
Please let me know if we got any information about it.

**Comment by JdaieLin** [comment]
Hi there, PiSugar 3 only support changing the i2c address for battery management (search Custom I2C address on the wiki page). We will consider add the changing support for the rtc i2c address in the coming firmware.

**Comment by nvmd** [comment]
Hi @JdaieLin,
I'm just wondering was the feature of changing RTC address ever implemented? Should this issue be reopened or a new one created?

It would be great to have this feature, as one of screens for RaspberryPi Zero (namely [Waveshare 2.13inch HAT+ V4](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT+)) which is very often used in combination with PiSugar, now also includes DS3231 on board, making use of this popular modules together quite problematic.
