### ISSUE TITLE
New Firmware 1.3.4 bricks the board

### ISSUE THREAD

**Issue by danielmorozoff** [PiSugar/PiSugar#118]
Installed new firmware according to docs -- it broke the board - could not use the batter. Had to hard reset firmware to receive functionality back

https://app.warp.dev/block/Eqy3BotZHkFWagXxtme5hO

**Comment by azufall** [comment]
Do you mean 1.7.4? That is the current release, Sept 7 2022. What version did you fall back to?

**Comment by JdaieLin** [comment]
@fengyc

**Comment by aymanbagabas** [comment]
This happened to me yesterday, how can I unbrick?

**Comment by JdaieLin** [comment]
This may occur if the upgrade process is interrupted. Please contact pisugar.zero@gmail.com for more product support, thank you!
