### ISSUE TITLE
Pisugar2 swollen battery

### ISSUE THREAD

**Issue by hulsr01** [PiSugar/PiSugar#120]
A few months ago, I purchased the Pisugar2. After using it a few times, I charged the battery and did not use it for 2 months. The battery was stored in a conditioned environment. Now, when I tried to turn it on again, I noticed that the battery had swollen. I would like to report this issue and kindly request a replacement battery pack from you.

![20230709_195339](https://github.com/PiSugar/PiSugar/assets/19633065/68ef5e66-ad74-418b-a4a5-0c05907178ef)
![20230709_195409](https://github.com/PiSugar/PiSugar/assets/19633065/b2504dbc-a0b9-4e86-b179-581130fb0e3b)
![20230709_195342](https://github.com/PiSugar/PiSugar/assets/19633065/4cb905a6-b3f8-477c-9cda-6838fb011d27)
![20230709_195404](https://github.com/PiSugar/PiSugar/assets/19633065/c975220e-9b71-46c1-86ed-9df3de1f28a8)
![20230709_195420](https://github.com/PiSugar/PiSugar/assets/19633065/d3235618-519b-478e-8003-b0fa344754c7)

**Comment by JdaieLin** [comment]
Hi @hulsr01, please contact pisugar.zero@gmail.com to request a replacement.
