### ISSUE TITLE
SCL Wake up is not working

### ISSUE THREAD

**Issue by gmagendzo** [PiSugar/PiSugar#122]
Hey all, I set up the the 3rd bit of the 0X20 address to 1 by using `i2cset -y 1 0x57 0x20 0x48` in order to enable the SCL awakening function, but it doesn't seem to be working correctly. I disconnected power to the PiSugar3 and shutdown the RPi4, but when I connect power back to the PiSugar3 it doesn't seem to boot the RPi4. Not sure what I'm doing wrong here, and would love some guidance in order to get the functionality working.

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by herrfrei** [comment]
The issue is not solved. Have the same right now also. The register cannot be written (value does not change):

```sh
i2cset -y 1 0x57 0x20 0x88
i2cget -y 1 0x57 0x20
0xc0
```
