### ISSUE TITLE
Anti mistaken touch Pishugur 3 turning off

### ISSUE THREAD

**Issue by fr0lnx** [PiSugar/PiSugar#123]
I have safe shutdown with custom shutdown shell and anti mistaken touch. When I hold the power button to shut it down anti mistaken touch is turned off.

**Comment by JdaieLin** [comment]
Sorry, I didn't understand the situation you described. Custom shutdown shell is for the custom button and the anti mistaken touch only is for the power button. They are not related.
For more product support please contact pisugar.zero@gmail.com. Thanks!

**Comment by Bluefrog922** [comment]
It was a while ago and I was talking about the custom shutdown script but I think it was my fault because the script didn’t end when run.
