### ISSUE TITLE
[Question] Can you set PiSugar 3 to boot more than once a day?

### ISSUE THREAD

**Issue by phalse** [PiSugar/PiSugar#126]
I just go my PiSugar3 working with a RPI Zero WH and want to know if it is possible to set the PiSugar to wake up the Pi more than once a days (web UI only specifies one time per day).  Can you do this though the cli API?

**Comment by wombat135** [comment]
I have the same request.

**Comment by phalse** [comment]
As a work around solution, I just ended up writing a script that ran at boot. The script queries the Sugar for current time, then adds X hours and sets the alarm for current time + X, then shuts down.

**Comment by wombat135** [comment]
I was going to do the same as you. Date+X then shutdown.  As I was playing the Sugar a little more, I realized that when I set an rtc_alarm via the WebUI or via the CLI, it only powers the pi when the pi sugar is completely turned off.  I cannot figure out a way to turn the pi sugar off without using the physical button/switch.

End state is to have a pi that is remote that turns on every couple of hours, does a few tasks, and then turns off.

**Comment by jacrooke** [comment]
Have you figured out a way to turn the PiSuagr off yet? Would you mind sharing an example of the script you ended up using for setting an alarm for a future time then shutting down your Pi?

**Comment by JdaieLin** [comment]
> As a work around solution, I just ended up writing a script that ran at boot. The script queries the Sugar for current time, then adds X hours and sets the alarm for current time + X, then shuts down.

This method is feasible because RTC can only store one alarm clock, so you can only set the next alarm clock at startup.
