### ISSUE TITLE
pisugar 2 power issues

### ISSUE THREAD

**Issue by githubesson** [PiSugar/PiSugar#127]
hello,

having some issues with the batterypack, where if i switch it on while theres no power running through the pi zero w board and it doesnt want to turn on. ideas?

**Comment by bowdena** [comment]
I'm not sure if this is the same issue, I have a pisugar 2 pro with a zero (and a zero 2), the unit powers on but shuts down within a minute when the management software is running.  Is this the same as you or do you get no power at all?

**Comment by githubesson** [comment]
havent bothered with the software, my pi0w crashes every time i try to install it hahaha

**Comment by githubesson** [comment]
(missclick)

**Comment by bowdena** [comment]
Sounds like a different issue, sorry to waste your time.

**Comment by githubesson** [comment]
No worries mate

**Comment by githubesson** [comment]
-

**Comment by githubesson** [comment]
-

**Comment by githubesson** [comment]
\-
