### ISSUE TITLE
Incorrect URL in pisugar-power-manager.sh and hardcoded version/package/architecture in PiSugarUpdate.sh on the PiSugar CDN

### ISSUE THREAD

**Issue by seelenamt** [PiSugar/PiSugar#130]
In pisugar-power-manager.sh, [referenced on this wiki page](https://github.com/PiSugar/PiSugar/wiki/PiSugar-3-Series#software-installation), line ~~116~~ **122** says
`package_programmer="pisugar-programmer_${version}-${rpm_n}.${arch_rpm}.rpm"`
where the underscore between "programmer" and "${version}" should actually be a dash (e.g. links it should use: [armv7hl](http://cdn.pisugar.com/release/pisugar-programmer-1.7.7-1.armv7hl.rpm), [aarch64](http://cdn.pisugar.com/release/pisugar-programmer-1.7.7-1.aarch64.rpm)), the link with an underscore doesn't lead anywhere for either architecture (e.g. links it actually uses: [armv7hl](http://cdn.pisugar.com/release/pisugar-programmer_1.7.7-1.armv7hl.rpm), [aarch64](http://cdn.pisugar.com/release/pisugar-programmer_1.7.7-1.aarch64.rpm))

and, secondly:

In PiSugarUpdate.sh, [referenced on the same wiki page as above, further down under OTA firmware upgrade](https://github.com/PiSugar/PiSugar/wiki/PiSugar-3-Series#new-features), lines 19, 20, and 47 are hardcoded to use programmer 1.6.4 (now out of date) and only in a deb package for armhf architecture. There is also a very minor typo (will not effect function) in line 25 where it says "stoping" instead of "stopping".

Normally, I'd do a pull request but the files in question aren't hosted anywhere on github from what I've seen.
I'm not sure if there is any specific reason that these and the firmware source aren't hosted on github (proprietary?), [though there is a repository with some generic "hello world" code](https://github.com/PiSugar/pisugar-3-driver), but it might be good for preservation's sake to keep these files here on github too, assuming that there isn't some proprietary reason preventing it.

Thanks!

**Comment by JdaieLin** [comment]
@fengyc
