### ISSUE TITLE
Too hot

### ISSUE THREAD

**Issue by jjsainzc** [PiSugar/PiSugar#132]
The case must be holes, are you testing the temperature ?

**Comment by JdaieLin** [comment]
Hi jjsainzc, in extreme cases, charging at maximum current may reach 60-80 degrees Celsius, and reaching 40 degrees Celsius at full load discharge.

**Comment by jjsainzc** [comment]
this temperature are unacceptable because the modem attached on top starts working with error

**Comment by JdaieLin** [comment]
There may not be a good solution to this situation. The only solution for the time being is to add a cooling fan.

**Comment by jjsainzc** [comment]
The best solution is change the design add holes

Best regards
73's HC1LNM
https://www.qrz.com/db/HC1LNM
+593 98 443 0010


Jorge Jesus Sainz Casalla
Freelance senior software developement and consultant.
