### ISSUE TITLE
I Cant turn OFF Pisugar3

### ISSUE THREAD

**Issue by rod85dev** [PiSugar/PiSugar#133]
I cant turn off the Pisugar3.

I hold the power button but the blue light stay on.

Is my unit defective?

Regards

**Comment by Gvieiraleao** [comment]
Same here

**Comment by globulas21** [comment]
I also have the same issue.

**Comment by egallis31** [comment]
same here - full hold of power button for over 60s does not power down

**Comment by JdaieLin** [comment]
Hi everyone, if the problem still exist please contact pisugar.zero@gmail.com for replacement and more product support.
