### ISSUE TITLE
Custom shell power on

### ISSUE THREAD

**Issue by Docfch** [PiSugar/PiSugar#135]
Hi everyone,
I have the pisugar 3 plus, i installed the webgui and i want to set a custom shell to power on for a single tap.
What is the command line i should put ?
Thanks.

**Comment by JdaieLin** [comment]
Hi Docfch, if you are using the webUI then you can set the singleTap option to "custom shell",  there should be a button appeared behind, click it to input your shell. 
If you a using command line: 
```
set_button_enable single 1
set_button_shell single YOUR_SHELL
```
