### ISSUE TITLE
custom battery

### ISSUE THREAD

**Issue by Docfch** [PiSugar/PiSugar#136]
Hello everyone,
I want to put this battery : https://fr.rs-online.com/web/p/piles-rechargeables-taille-speciale/1449405
Is it possible ?
Thanks.

**Comment by Docfch** [comment]
or this : https://www.amazon.de/-/en/dp/B095BTSMYH?ref=emc_s_m_5_i_atc

**Comment by JdaieLin** [comment]
Hi Docfch, both of the them are ok to be connected to PiSugar.
