### ISSUE TITLE
Battery NEVER stops charging? (LED lights NEVER stop blinking)

### ISSUE THREAD

**Issue by Dochartaigh** [PiSugar/PiSugar#137]
PiSugar 3, 1200mah, bought from Amazon

The battery seems to NEVER stop charging? (LED lights NEVER stop blinking). Even when it's detached from the Raspberry Pi (which I don't know if I HAVE to install special software on the Raspberry Pi Zero 2 W itself to make it stop charging?). I let it charge on a known-working USB-C cable/charging-brick and 20+ hours and those LED's are STILL blinking!

Am I doing something wrong? Any fix?

**Comment by JdaieLin** [comment]
Hi Dochartaigh, it won't stop blinking is the cable is connected and actually it's not in charging status. We will try fixing this bug in the future version. Thanks for your feedback!

**Comment by drego85** [comment]
Hello, the problem persists.

Are there any updates on when it will be resolved?

Thanks 

PS. Another thread: https://github.com/PiSugar/PiSugar/issues/119

**Comment by GuardianZX9** [comment]
I have this issue with a unit I purchased on 6-6-2026  Any updates?

**Comment by clong** [comment]
Same, except mine shows the charging indicator lights even with the cable disconnected. 

The device shows: 
```
battery_charging: true
battery_power_plugged: true
```
even with nothing plugged in
