### ISSUE TITLE
[PiSugar 3] What connector to use with extension interface?

### ISSUE THREAD

**Issue by Manish181992** [PiSugar/PiSugar#142]
Hi PiSugar team,

There is no information on the connector type to use with PiSugar 3 extension interface on the wiki. Can you please provide that?
Does it use a 6-Pin JST SH connector with 1.0 mm pitch?

Thanks

**Note:** This repo is mainly about the entire PiSugar project, cases and wiki. We usually process these issues once a month. For quick response about PiSugar products, please contact pisugar.zero@gmail.com. For software issues, please submit your issuse to https://github.com/PiSugar/pisugar-power-manager-rs/issues

**Comment by JdaieLin** [comment]
Hi Manish, it use a 6 Pin connector with 1.27mm pitch.
