### ISSUE TITLE
PiSugar2 Portable 1200 - External Power Button

### ISSUE THREAD

**Issue by ranasats** [PiSugar/PiSugar#143]
I want to connect an external power button to the PiSugar2 Portable for my rpi zero. Can someone provide the pins which should be connected to a switch in order to accomplish this? I would like to put the zero in a case and I wouldn't have easy access to the standard power switch anymore. The switch I have is a normal on-off switch: https://www.adafruit.com/product/482

The documentation from the other 'issues' here: https://github.com/PiSugar/PiSugar/issues/116 say that for the S model there are ctrl on off pads. I don't see those pads on the Sugar Portable. 

Thanks, @wlmh110 for your help :) 

**EDIT**
Testing I found these two pads in red, when either one is connected to the ground pad, will turn OFF the pisugar while the switch is in the ON position. I want to confirm that bridging one of those with the ground won't cause any harm for extended period of time. 
![image](https://github.com/PiSugar/PiSugar/assets/29738245/4942dd5a-3c04-48f6-acd3-42e0e203bbe6)

**Comment by JdaieLin** [comment]
Here are the instructions for connecting an external switch to the PiSugar2:

Turn the switch to the ON position.

Solder three pads as shown in the diagram below.

When 1 and 2 are connected, the device will turn on. When 2 and GND are connected, the device will turn off.

![image-2](https://github.com/PiSugar/PiSugar/assets/12379831/e3d7cc66-16a8-4e61-8c50-739098172955)

Don't worry about a short circuit when 2 and GND are connected. The switch uses a pull-up resistor, so the current is very small when 2 is connected to GND.
