### ISSUE TITLE
Pi 5

### ISSUE THREAD

**Issue by TLMcNulty** [PiSugar/PiSugar#144]
I have Pisugar 3 Plus and a Raspberry Pi 5. 

Slapping it on as I would a Pi 4B doesn't work the same. It probably wasn't designed to do this but is there any way to make it work?

**Comment by TLMcNulty** [comment]
I was mistaken! The pi 5 GPIO through pins are smaller than earlier models. Be very careful when lining the boards up and they should work well! Awesome product!

**Comment by JdaieLin** [comment]
![116171721119059_ pic](https://github.com/user-attachments/assets/cde57403-bc0e-4ead-a3fa-6b8787677988)
 If there is flux on Pi 5 (pictured), be sure to remove it in advance before installing PiSugar.
