### ISSUE TITLE
Does PiSugar 3 Plus have current monitoring feature like INA219?

### ISSUE THREAD

**Issue by beitong95** [PiSugar/PiSugar#146]
Hi I was wondering if the battery management chip used by PiSugar 3 Plus can output the current, or the power in Watt used by the raspberry pi.

**Comment by JdaieLin** [comment]
The output voltage of battery can be queried via software. But not the current, it's not accurate when charging.

**Comment by funkymonkey5150** [comment]
I know that the battery output can be queried yeah I know the battery
status could be worried and so therefore I'm pretty sure status and any
other information can also be retrieved queried or requested
