### ISSUE TITLE
SCL Wake up is not working in 2024!

### ISSUE THREAD

**Issue by herrfrei** [PiSugar/PiSugar#152]
The issue is not solved. Have the same right now also. The register cannot be written (value does not change):

```sh
i2cset -y 1 0x57 0x20 0x88
i2cget -y 1 0x57 0x20
0xc0
```

_Originally posted by @herrfrei in https://github.com/PiSugar/PiSugar/issues/122#issuecomment-2386683278_

**Comment by JdaieLin** [comment]
@fengyc

**Comment by JdaieLin** [comment]
You need to write 0x29 to 0x0B to disable write protection before writing 0x20.

**Comment by herrfrei** [comment]
Ah, I see. Many thanks for clarification!
