### ISSUE TITLE
Problem installing power manager

### ISSUE THREAD

**Issue by sylarr** [PiSugar/PiSugar#22]
When trying to install power manager i got this message "curl: (6) Could not resolve host: cdn.pisugar.com"

**Comment by JdaieLin** [comment]
Hi, where is your location? We need to check the accessibility of the CDN.

**Comment by JdaieLin** [comment]
We've change the region to global. You can try a again later.

**Comment by beautifulmount** [comment]
Hi, still not working. I'm in Italy.

**Comment by JdaieLin** [comment]
If it's still not accessible, you should download the pisugar-server an pisugar-poweroff from:
https://github.com/PiSugar/pisugar-power-manager-rs/releases/tag/v1.4.8

and install them using script:
dpkg -i xxx.deb

**Comment by beautifulmount** [comment]
The dpkg seems to work fine but then appears "connection closed by the remote host" and since then the pi fail to boot

**Comment by JdaieLin** [comment]
@fengyc

**Comment by fengyc** [comment]
> The dpkg seems to work fine but then appears "connection closed by the remote host" and since then the pi fail to boot

@beautifulmount  Any screenshots or systemd log?

**Comment by pcfreaxx** [comment]
I have the same Problem. I am in Germany but also with Hongkong vpn still curl could not resolve host cdn.pisugar.com
I send my pisugar2 back. Without working Software, it is just an expensive battery.

**Comment by invictusani** [comment]
@JdaieLin I'm having install the software as well, im located in the US. I get the code curl: "(6) Could not resolve host: cdn.pisugar.com"

any advice?

**Comment by pcfreaxx** [comment]
@invictusani this error is known. Go on GitHub and download each package file by Hand and Install via dpkg -i

**Comment by invictusani** [comment]
@pcfreaxx dang alright, ill do that. LOL yeah im having a hard time getting this thing set up.

thanks again for the help!

**Comment by randoassuser** [comment]
why exactly does it not work via curl? problem with your ssl certificates?
and how to install the packages via dpkg -i
