### ISSUE TITLE
Question - Solar Power

### ISSUE THREAD

**Issue by mikev1963** [PiSugar/PiSugar#23]
Can I hook up a solar panel to charge battery while using the Pi Sugar Pro?  

Not sure where rot ask questions.

**Comment by JdaieLin** [comment]
Yes you can. The solar panel should have its own output board, connect it to the 5V input pads.

**Comment by JdaieLin** [comment]
'qi' VIN and GND

**Comment by PEBL-CIC** [comment]
Hi, so you have to use a separate charge controller between the panel and the PiSugar? Do you recommend any boards for this use?

**Comment by machs123** [comment]
I have a PiSugar 3 I would like to charge using a 5V solar panel.  This thread suggests such panels should be connected to the qi input of the PiSugar 3 board.  My question relates to the maximum input voltage the board allows.  I am considering a solar panel specified for 5V and 5W.  However, this panel has the following additional specifications - 6.13V peak and 7.13V open circuit.  Can the PiSugar 3 qi input handle these voltages?  I just don't want to damage my new PiSugar 3.  Alternately, I assume the PiSugar 3 uses a power management IC to manage the battery, AC adapter and qi inputs used for charging the battery.  If someone can tell me what IC is used I could look it up and share my experience with others having similar questions.  I really like my PiSugar 3 and look forward to someone helping me with this.

**Comment by seschu** [comment]
> I have a PiSugar 3 I would like to charge using a 5V solar panel. This thread suggests such panels should be connected to the qi input of the PiSugar 3 board. My question relates to the maximum input voltage the board allows. I am considering a solar panel specified for 5V and 5W. However, this panel has the following additional specifications - 6.13V peak and 7.13V open circuit. Can the PiSugar 3 qi input handle these voltages? I just don't want to damage my new PiSugar 3. Alternately, I assume the PiSugar 3 uses a power management IC to manage the battery, AC adapter and qi inputs used for charging the battery. If someone can tell me what IC is used I could look it up and share my experience with others having similar questions. I really like my PiSugar 3 and look forward to someone helping me with this.

ever found a solution? @machs123

**Comment by robertlagrant** [comment]
I'd also love to know if anyone's done this, and what panel they used.

**Comment by funkymonkey5150** [comment]
Best regards,Steve PlasenciaBusiness Development ManagerCell: (323) 573-1967https://calendly.com/steve-plasencia/staffing_servicesOn Sep 22, 2026, at 5:05 AM, Robert Grant ***@***.***> wrote:﻿robertlagrant left a comment (PiSugar/PiSugar#23)
I'd also love to know if anyone's done this, and what panel they used.

**Comment by funkymonkey5150** [comment]
Best regards,Lm> wrote:﻿robertlagrant left a comment (PiSugar/PiSugar#23)
I'd also love to know if anyone's done this, and what panel they used.
