### ISSUE TITLE
Compatibility with Dual Quad SATA Radxa

### ISSUE THREAD

**Issue by jalasso** [PiSugar/PiSugar#26]
Just wondering if you you help me out figure out issues I am having with https://wiki.radxa.com/Dual_Quad_SATA_HAT#Power_Options installed on raspberry pi4 and Pisugar 2 pro. For some reason those two cards conflict. The piout for radxa card is one the link I pasted. Can you please be so kind and take a look at it and compare it with the pinout of pisugar. I really like to use it on my project, a NAS server.

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by wlmh110** [comment]
Hi,
Could you please use the follow comands to see what the I2C trasnfer?
i2cdump -y 1 0x32
i2cdump -y 1 0x75
