### ISSUE TITLE
Check if battery is charging

### ISSUE THREAD

**Issue by rafael** [PiSugar/PiSugar#3]
### Desc 

Hi! I received my battery today and I'm running some tests. I have a question: 

If I have this battery connected to a raspberry pi, how can I check if the battery is charging? (i.e I would like to write a small program that detects if pisugar is charging/not charging). The ultimate goal is to detect if the raspberry pi is running from the battery or there is power available. 

Thanks!

**Comment by JdaieLin** [comment]
Hi rafael, the first version is just providing power to pi, no data connection. Thus there is no way to detect the battery level or detect whether it is charging. 

We are working on a newer version which will have the abilities you need. New hardware prototypes are under testing. Also I am writing the program to work with it:
https://github.com/PiSugar/pisugar-power-manager

I will update the progress on Hackaday.io:
https://hackaday.io/project/164733-pisugar-battery-for-raspberry-pi-zero

Thanks!
