### ISSUE TITLE
Webpage sets disabled on open

### ISSUE THREAD

**Issue by GSVNoFixedabode** [PiSugar/PiSugar#30]
I've noticed that if you go to the power management webpage, it automatically resets the next wakeup to 'disabled' as soon as the page is displayed.  Can this be changed so that it doesn't change the current setting on the board, but shows what is in the board memory?
[Edit] PiSugar2, Raspberry Pi ZeroW

**Comment by JdaieLin** [comment]
This bug has been fixed in the least version.
