### ISSUE TITLE
Pi Zero W - Installation Error

### ISSUE THREAD

**Issue by RaistlinD2x** [PiSugar/PiSugar#31]
Issue during wget. Also, do you have any documentation on how best to interface with the device in the headless state? Without the gui I'm not sure how to setup parameters.

![image](https://user-images.githubusercontent.com/73706463/107670394-4d9d2c00-6c58-11eb-8ed1-83884291657d.png)

**Comment by GSVNoFixedabode** [comment]
Try changing security, ie run with **sudo** wget...

**Comment by JdaieLin** [comment]
Please try install with bash
`curl http://cdn.pisugar.com/release/Pisugar-power-manager.sh | sudo bash`
