### ISSUE TITLE
Modeling missing parts

### ISSUE THREAD

**Issue by wnark** [PiSugar/PiSugar#33]
![image](https://user-images.githubusercontent.com/24355466/109474742-c9e49b80-7aaf-11eb-811a-d33cc13510d5.png)

**Comment by JdaieLin** [comment]
在打开什么文件的时候出现这个提示？

**Comment by wnark** [comment]
> 在打开什么文件的时候出现这个提示？

打开\PiSugar-master\PiSugar-master\model\pisugar_case_all.SLDPRT
文件的时候的提示，我搜了下全部文件没有叫pisugar_case_camera_cap.SLDPRT的文件
