### ISSUE TITLE
Extend activate button?

### ISSUE THREAD

**Issue by danielfaulknor** [PiSugar/PiSugar#35]
Just before I buy a couple of Pro2's, I assume it would be possible to solder wires onto the activate button pins and, for example, use a relay to "press" the activate button to power on a shutdown Pi?

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by wlmh110** [comment]
Hi，
The active button only used when removing the battery or the battery level is very low, so it's not in common use.
If you want to open the PiSugar remote, you can try to solder wires on the switch.
There are 3 pins of the switch, the middle pin controls the operation of the system.

**Comment by danielfaulknor** [comment]
Thank you!

**Comment by jan94** [comment]
Can you provide some schematics for how to extend the power button ?
