### ISSUE TITLE
Problem to turn on the PiSugar

### ISSUE THREAD

**Issue by tXambe** [PiSugar/PiSugar#36]
Hello,

Yesterday I was work without problem with the PiSugar, the battery was overwhelmed
and now don't charge and don't turn on, What I can do ?

A greeting and thanks

**Comment by JdaieLin** [comment]
Hi, if you are using the Pro version, you should press activation button when the switch is off and being charging.
If still cannot turn on, please contact PiSugar.zero@gmail.com from support.
