### ISSUE TITLE
Power Management not working

### ISSUE THREAD

**Issue by feh123** [PiSugar/PiSugar#38]
Hi I have a PiSuger 2 (2-leds) running on an RPi0 with the Raspberry Pi OS 32bit. Everything seems to install fine - systemctl status shows pisugar server running and journalctl pisugar server shows no errors. 

I can open the ip:8421 in my browser and set wake up, sync RTC, and select a button action. In journalctl I see all these actions and I get no errors. Yet I can select long or double tap for shutdown and these actions once set do nothing. The RPi0 remains on.

Am I missing something? Thanks.

**Comment by JdaieLin** [comment]
Hi, try opening the management webpage to check whether the server can receive button events. If can, there should be a green tag show up on the right of button setting when you press the button.
Please contact PiSugar.zero@gmail.com for more support.
