### ISSUE TITLE
PiSugar2 PowerPack M

### ISSUE THREAD

**Issue by AntoineTurmel** [PiSugar/PiSugar#40]
Is a PiSugar2 PowerPack M planned ?
The PiSugar1 PowerPack M is not available anymore online...

**Comment by JdaieLin** [comment]
Hi Antonie,
We currently have no plan for the 900mah version. Please contact us via ***@***.*** if you have need for this model. Thanks!







------------------ Original ------------------
From: Antoine Turmel ***@***.***&gt;
Date: Tue,Apr 20,2021 11:03 PM
To: PiSugar/PiSugar ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [PiSugar/PiSugar] PiSugar2 PowerPack M (#40)





 
Is a PiSugar2 PowerPack M planned ?
 The PiSugar1 PowerPack M is not available anymore online...
