### ISSUE TITLE
Charge setting not storing for 100%

### ISSUE THREAD

**Issue by causalloop** [PiSugar/PiSugar#43]
Using the web interface, the battery charge setting will save for values < 100.  Can't seem to use the CLI for thi either.  "get battery" just returns an "invalid request".  Other settings I can get but a good chunk of the don't work.

**Comment by JdaieLin** [comment]
@fengyc

**Comment by bgilreath** [comment]
Same response to running "echo "get battery" | nc -q 0 127.0.0.1 8423" on Ubuntu 20.04 LTS. Was working at one point.
