### ISSUE TITLE
[PiSugar2] Fragile power switch 

### ISSUE THREAD

**Issue by hijackeel** [PiSugar/PiSugar#45]
When I tried to use the power switch, the sliding tab snapped off the actual component. Now I need to desolder and replace it. Part of this is due to bad tolerances on the case (see issue #44), but choosing a different power switch would help.

**Comment by hijackeel** [comment]
@JdaieLin : Could you tell me what the part number is of the current switch, so I can order a replacement?

**Comment by JdaieLin** [comment]
Hi, hijackeel. Please contact pisugar.zero@gmail.com for replacement, thanks!
