### ISSUE TITLE
External switches.

### ISSUE THREAD

**Issue by bongoplayingmonkey** [PiSugar/PiSugar#47]
I need to install the pisugar 2 pro into a case where the power switch isn't accessible. Any tips for adding in an external switch to solve that issue?

**Comment by bongoplayingmonkey** [comment]
Can there at least be some JST sockets to extend the switches out to surface mounts on future versions?

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by GSVNoFixedabode** [comment]
Any update on this?  I have the same requirement.

**Comment by wlmh110** [comment]
Here is the PCB of the PiSugar 2 Pro power switch.
![image](https://user-images.githubusercontent.com/37292630/129534515-848ac052-ee80-428c-a37b-1e94923fbed8.png)
When the 2(VOUTC1) pin is connected with 3(VOUT1), PiSugar will work, and when the 2(VOUTC1) pin is connected with 1(GND), it will shut down.

**Comment by fheslouin** [comment]
@wlmh110 where can we find those pins ? PCB is not showing any of these names

**Comment by sledgehammer617** [comment]
Any updates on this? Anyone figure out how to do it? 

I was also hoping to install my pisugar 2 pro in a case with an external button.

**Comment by Acluff1** [comment]
I figured it out! Simply solder your toggle switch wires to "Ctrl" and "Off," leave the main switch in the "On" position and bam! 
![Uploading 20220314_203003.jpg…]()

**Comment by sledgehammer617** [comment]
@Acluff1 Cool, thanks!

**Comment by sjin4903** [comment]
@HaochengZheng 
I want to know exactly where you're connecting.

**Comment by HaochengZheng** [comment]
After you remove the metal cap over the switch and the plastic handle, there are 3 metal areas underneath. Originally, when the switch is at "off", middle and left metal areas are connected; when the switch is at "on", middle and right part is connected. So get a slide switch, solder 3 pins of slide switch to each metal area(right pin- right, middle-middle, left-left)

**Comment by HaochengZheng** [comment]
@sjin4903 
After you remove the metal cap over the switch and the plastic handle, there are 3 metal areas underneath. Originally, when the switch is at "off", middle and left metal areas are connected; when the switch is at "on", middle and right part is connected. So get a slide switch, solder 3 pins of slide switch to each metal area(right pin- right, middle-middle, left-left)

**Comment by sjin4903** [comment]
@HaochengZheng 
Problem solved! Thanks

**Comment by stokes776** [comment]
Any idea if I want to just connect a switch that has two leads, not three?

OFF = Middle and LEFT so...... X X o
ON = Middle and Right          o X X

Feels like maybe I could just ignore that orange wire you have in your photo?

**Comment by HaochengZheng** [comment]
@stokes776 I don't think so. I guess there is some kind of capacitor, so you have to make MIDDLE and LEFT pad connected before switching to MIDDLE and RIGHT

**Comment by spaceman1988** [comment]
> I figured it out! Simply solder your toggle switch wires to "Ctrl" and "Off," leave the main switch in the "On" position and bam! I should add this was a pisugar S plus.
> 
> ![20220314_203003](https://user-images.githubusercontent.com/101166641/158400168-ef664a39-6f18-4df9-9ffb-9d221c6188d8.jpg)

I have an "S". The document isn't very clear on what the CTRL-OFF-ON pinouts actually do. Do the pinouts control power going to the Pi (turning power on and off), or do the pins set the state of the Pi's GPIO3?

I have a Pi Screen installed and can safely shutdown the Pi from the screen, but since it's in a case I need a way to turn in back on. Referring to your photo, I'm assuming these pins are controlling power to the Pi your toggle switch in one direction would take power away from the Pi and flipping it the other way would turn it back on. Correct? If all I wanted to do was turn it back on from screen-triggered shutdown then a momentary pushbutton between CTRL and OFF should do the trick.
