### ISSUE TITLE
Broken micro-usb port - PiSugar V1

### ISSUE THREAD

**Issue by mlinton** [PiSugar/PiSugar#5]
The micro-usb port broke off of the pcb, and I'd like to re-attach it or find out where the 5v and ground from the USB port can be soldered elsewhere on the board.

**Comment by JdaieLin** [comment]
Hi, mlinton. Please contact pisugar.zero@gmail.com to send you a replacement board. It will be easier to re-attach the battery than a usb port.

**Comment by dadav** [comment]
Hello, i got the same problem. Will contact you too
