### ISSUE TITLE
PiSugar has slow response for command queries on Bullseye

### ISSUE THREAD

**Issue by ghost** [PiSugar/PiSugar#52]
I have a few Pi's + PiSugar's and all work fine with Dietpi, except the new Bullseye version - the PiSugar is very sluggish to respond to commands. 

The settings are duplicated with the working ones, so is there some issue with bullseye and PiSugar?

I swapped the PiSguars from the the working ones to the sluggish one, and its appears to be the Bullseye version that's causing it - there was no issue with the h/w, its just when PiSugar is used with Bullseye it appears to be the problem.

+-------- Pi-3B Buster Settings **NO ISSUES** --------+
                 Serial/UART      : Manage available devices                       │
│                 Bluetooth        : [Off]                                          │
│                 I2C state        : [On]                                           │
│                 I2C frequency    : [100 kHz]                                      │
│                 SPI state        : [Off]                                          │

+-------- Pi-4B Buster Settings **NO ISSUES** --------+
  Update RPi4 EEPROM firmware : [Bootloader: 1599135103 | VL805: 000138a1]   │
│  Serial/UART                 : Manage available devices                     │
│  Bluetooth                   : [On]                                         │
│  I2C state                   : [On]                                         │
│  I2C frequency               : [100 kHz]                                    │
│  SPI state                   : [On]                                         │

```
+-------- Pi-4B Bullseye Settings (** HAS ISSUES ***)--------+
     Update RPi4 EEPROM firmware : [Bootloader: 1619712685 | VL805: 000138a1]      │
│     Serial/UART                 : Manage available devices                        │
│     Bluetooth                   : [Off]                                           │
│     I2C state                   : [On]                                            │
│     I2C frequency               : [100 kHz]                                       │
│     SPI state                   : [Off]                                           │
or 
│     SPI state                   : [On]                                           │
```
Still has issues.

Any other settings I should check on PI4 Dietpi Bullseye?

**Comment by w1v1** [comment]
Same issue on Pi-4 and Pi-3, both bullseye.

**Comment by JdaieLin** [comment]
@fengyc

**Comment by fengyc** [comment]
Working on it ~
