### ISSUE TITLE
When triggering custom button function: getting error

### ISSUE THREAD

**Issue by snarflakes** [PiSugar/PiSugar#53]
I set up via my phone and the pisugar battery web interface   "thepath/.../sf.py" (a python file)
But it looks like a possible conflict between homebridge server and pisugar server when triggering the pi-sugar button.  Has anyone seen this before? This is what comes up on journalctl read out after pressing the pisugar accessory button. Or do I need to put the python file into a script and put that into the button link thing instead?

Aug 19 17:41:01 homebridge pisugar-server[305]: [2021-08-20T00:41:01Z INFO  pisugar_server] Websocket closed

repeated:
Aug 19 17:54:22 homebridge pisugar-server[267]: [2021-08-20T00:54:22Z INFO  pisugar_server] Websocket closed
Aug 19 17:54:22 homebridge pisugar-server[267]: [2021-08-20T00:54:22Z ERROR pisugar_server] Invalid

thanks,
Snarflakes

**Comment by wlmh110** [comment]
Hi,
Can you take out "sudo" and try again?
just:
python3 /home/pi/ganpunks/NFTGIFDisplay/QRCODElinker.py

**Comment by Zanop** [comment]
Hi,

I am getting the same issue, custom button commands generally work but I get these lines in the log constantly:

Nov 13 13:30:27 Curigotchi pisugar-server[243]: [2024-11-13T12:30:27Z ERROR pisugar_server] Invalid
Nov 13 13:30:41 Curigotchi pisugar-server[243]: [2024-11-13T12:30:41Z ERROR pisugar_server] Invalid
Nov 13 13:30:53 Curigotchi pisugar-server[243]: [2024-11-13T12:30:53Z ERROR pisugar_server] Invalid
Nov 13 13:31:04 Curigotchi pisugar-server[243]: [2024-11-13T12:31:04Z ERROR pisugar_server] Invalid
Nov 13 13:31:15 Curigotchi pisugar-server[243]: [2024-11-13T12:31:15Z ERROR pisugar_server] Invalid
(END)
