### ISSUE TITLE
没有apt,dpkg这种安装程序的极小Linux系统该如何安装pisugar 2

### ISSUE THREAD

**Issue by yq3w** [PiSugar/PiSugar#55]
树莓派zero,极小Linux系统没有apt,dpkg这种安装程序怎么安装pisugar 2?

**Comment by JdaieLin** [comment]
可以使用其他平台交叉编译，把可执行文件拷到zero上跑

**Comment by fengyc** [comment]
@yq3w 这种情况下，你需要把可执行文件下载下来，放到 /usr/local/bin 下，自行写一个 init-script 来在开机时启动服务。在 release 下的 https://github.com/PiSugar/pisugar-power-manager-rs/releases 的可执行文件不需要其它的库，可直接下载运行
