### ISSUE TITLE
Configuring custom button on PiSugar S

### ISSUE THREAD

**Issue by carrefinho** [PiSugar/PiSugar#57]
The feature comparison lists the PiSugar S as capable of turning off the Pi with the button. However I couldn't find information on how to enable this. How to configure the custom button?

**Comment by ashBabu** [comment]
Sorry, I am quite new to this and didnt understand. I have raspberry Pi 4 and pisugar 3 plus. how can i enable safe shutdown and boot up using pi sugar button
