### ISSUE TITLE
PiSugar 2 & On Power Restore

### ISSUE THREAD

**Issue by jpcetre** [PiSugar/PiSugar#59]
Hi,
I am playing with my new PiSugar2 (2 leds) and a Pi Zero W. 
I expected to use it as an UPS and found the On Power Restore option for the Schedule Wake Up, but I am not able to make it work. 
Any trick I should know?
(I tried to plug sugar and pi on 2 separate chargers but same result)

![image](https://user-images.githubusercontent.com/16814291/138018181-09cda447-ce9b-4c1d-85a4-d46526e84ff0.png)

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by wlmh110** [comment]
Hi,
Can it start up once? Or does it never starts up after shutdown?

**Comment by erlendv** [comment]
@wlmh110 Im experiencing the same thing. Just purchased pisugar2. I selected the on power restore option. After shutting the pi down, disconnected and reconnected power, nothing happens. A couple of things I noticed:
- after booting the pi (turning pisugar off and on) and going into the web interface a warning pops up that I have turned off wake-on-power-restore and the setting in the UI turns back to disabled
- however, in /etc/pisugar-server/config.json `auto_power_on` is `true`

**Comment by xlla** [comment]
I don't know where to ask a question, so post it here:
Can I use same power supply to charge the Pi and PiSugar while using feature "On Power Restore" ?
My purpose is when I turn on the power my device and Pi & PiSugar will be power on and start charge the PiSugar, when I turn  off the power , Pi will notice that and power off auto.

**Comment by wlmh110** [comment]
> I don't know where to ask a question, so post it here: Can I use same power supply to charge the Pi and PiSugar while using feature "On Power Restore" ? My purpose is when I turn on the power my device and Pi & PiSugar will be power on and start charge the PiSugar, when I turn off the power , Pi will notice that and power off auto.

You need to use different chargers, otherwise PiSugar will charge itself by battery

**Comment by wlmh110** [comment]
> @wlmh110 Im experiencing the same thing. Just purchased pisugar2. I selected the on power restore option. After shutting the pi down, disconnected and reconnected power, nothing happens. A couple of things I noticed:
> 
> * after booting the pi (turning pisugar off and on) and going into the web interface a warning pops up that I have turned off wake-on-power-restore and the setting in the UI turns back to disabled
> * however, in /etc/pisugar-server/config.json `auto_power_on` is `true`

We suspect it is a software bug. What version of software are you using now?

**Comment by Tetsujinfr** [comment]
@erlendv do you still experience that issue with the on pwr wake up function? If not, how did you fix it? (Software update, other?)

**Comment by bluefireexplosion** [comment]
Still experiencing this issue with a pisugar 2, auto_power_on is enabled. When shutting down the pi, removing power, then reconnecting power, the pi will not turn back on until the power switch is toggled. Any solutions?

**Comment by wlmh110** [comment]
> Still experiencing this issue with a pisugar 2, auto_power_on is enabled. When shutting down the pi, removing power, then reconnecting power, the pi will not turn back on until the power switch is toggled. Any solutions?

First, please update the latest software
Secondly, can you describe what happened after the external power supply was restored?

**Comment by kcmd** [comment]
> > Still experiencing this issue with a pisugar 2, auto_power_on is enabled. When shutting down the pi, removing power, then reconnecting power, the pi will not turn back on until the power switch is toggled. Any solutions?
> 
> First, please update the latest software Secondly, can you describe what happened after the external power supply was restored?

I'm experiencing the exact same problem described by bluefireexplosion. The latest software is installed. Being able to automatically turn the Raspberry Pi on again after power has been restored is an important capability for remotely installed devices that are being recharged by a solar panel.

**Comment by kcmd** [comment]
Likely relates to Issue #98.
