### ISSUE TITLE
PiSugar S Plus - External power off/on detection

### ISSUE THREAD

**Issue by noelanderson** [PiSugar/PiSugar#60]
I want to use a PiSugar S Plus to keep the RPi 4 alive for a controlled shutdown on losing power.

So on  External power off detection - Pi shuts down
On external power is restored - Pi Starts up

I'm assuming that to do this I don't use the Power Manager software, but instead us the dtoverlay=gpio-shutdown setting in /boot/config.txt.  Is this correct?

And if so, is this the right config setting?
dtoverlay=gpio-shutdown,gpio_pin=3,active_low=0,gpio_pull=down

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by wlmh110** [comment]
Hi，
We think it should work.
When the auto start switch it turn on, the GPIO3 active like this:
External power is available -> GPIO3 = 0
External power is unavailable -> GPIO3 = 1
