### ISSUE TITLE
PISugar S software

### ISSUE THREAD

**Issue by rodneygmorgan** [PiSugar/PiSugar#61]
The Pisugar-power-manager.sh doesn’t list the PiSugar S (for pi3b) as an install choice. Is there separate software for the ‘S’ version or which option do I choose for the ‘S’ version.

**Comment by JdaieLin** [comment]
PiSugar S is a replace version of PiSugar 1. Both of them have no i2c feature and there's no software supports.

**Comment by JdaieLin** [comment]
https://github.com/PiSugar/PiSugar/wiki/PiSugarS-Plus#function-comparison

**Comment by rodneygmorgan** [comment]
Thanks, looks like I could have read the documentation more thoroughly!
