### ISSUE TITLE
Qi used as 5V VIN but not charging

### ISSUE THREAD

**Issue by pauloesperon** [PiSugar/PiSugar#62]
Hi there, I would like to use the Qi pads to wire a USB-C female breakout board 5v input to I can put the charging port somewhere else on my enclosure instead of using the micro USB port. I wired it but it is not charging. Any idea what might be happening? 

As far as my wiring, from the break out board I connect the VBUS and GND to + and - Qi. 

Thank you!

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by wlmh110** [comment]
Could you please take a picture?

**Comment by dbrb2** [comment]
Should this work? I was hoping to do the same, but haven't yet wired it up...

**Comment by wlmh110** [comment]
As long as 5V power supply is input, it can work

**Comment by nachotisnes** [comment]
Did you manage to get this working? I'm facing the same issue. Sorry in advance if I make newbie errors, i'm kinda outside my comfort zone here.

I've been doing some measuring with my multimeter, and I'm getting the idea that the correct wiring may be the opposite one.

My measurements are:
- When the QI adapter is not plugged to the board and is "active", the voltage is 4.92
- When the QI adapter is wired as you mention, the output voltage from the adapter drops to ~0.3, and the adapter starts working erratically: it seems to be turning on and off.
- In that case, the battery is shown as "not charging" and continues discharging using the webUI, although using the command line sometimes I get a battery_charging=true.

@wlmh110 can you make something of this?

**Comment by wlmh110** [comment]
Hi, can you take a picture of the system?

**Comment by nachotisnes** [comment]
It was a dumb mistake in my part.

Seeing the pics I posted eariler y realized my mistake, I had the wires inverted (VIN/GND).

After correcting that the web UI shows a "Charging" status. Will continue my testing.

Thanks!
