### ISSUE TITLE
Provide STL or STEP for PiSugar boards and PiSugar battery

### ISSUE THREAD

**Issue by bgilreath** [PiSugar/PiSugar#66]
The models can be low fidelity and dimensionally accurate.

This would allow others to integrate into cases of different designs than one provided.

I was not able to locate within the current documentation.

**Note:** This repo is mainly about the entire PiSugar project, cases and wiki. We usually process these issues once a month. For quick response about PiSugar products, please contact pisugar.zero@gmail.com. For software issues, please submit your issuse to https://github.com/PiSugar/pisugar-power-manager-rs/issues

**Comment by JdaieLin** [comment]
Good suggestion. I will upload the pisugar STL models this weekend.

**Comment by JdaieLin** [comment]
You can find the boards' STL here:

https://github.com/PiSugar/PiSugar/blob/master/model2/pisugar2Board.STL
https://github.com/PiSugar/PiSugar/blob/master/model3/pisugar3Board.STL
https://github.com/PiSugar/PiSugar/blob/master/model_pro/pisugar2pro.STL
https://github.com/PiSugar/PiSugar/blob/master/model_pro/pisugar3plus.STL

**Comment by bgilreath** [comment]
Thanks!
