### ISSUE TITLE
Parameters for 3D Printing the case

### ISSUE THREAD

**Issue by AntoineTurmel** [PiSugar/PiSugar#7]
Hello, what are the best parameters to get a clean 3D print of the case?
- Rafts ? Using PVA ?
- Supports ?
- Resolution ?
- Infill % ?
- Material ?
- 3D Printer you use ?

**Comment by AntoineTurmel** [comment]
I'll try with:
- PVA Rafts
- Supports (plate adhesion)
- 0.1mm resolution
- 20% Infill
- Tough PLA Black
- Printing with Ultimaker 3 Extended

**Comment by JdaieLin** [comment]
Hi, Antonie. We usually commission a professional factory to print these cases. 
Here's some detail I can provide:

- They use large industrial SLA printers (UnionTech or HP)
- STL model tolerances and angles usually set to 0.0045mm and 6.333
- Material: Somos GP resin (tolerances 200μm)

You can get a quote by uploading the STL files to their website: https://www.wenext.hk. I am not sure about their oversea shipping fee. 

If you would like to get a ready to use case from us, please contact pisugar.zero@gmail.com.

**Comment by JdaieLin** [comment]
> I'll try with:
> 
> * PVA Rafts
> * Supports (plate adhesion)
> * 0.1mm resolution
> * 20% Infill
> * Tough PLA Black
> * Printing with Ultimaker 3 Extended



> I'll try with:
> 
> * PVA Rafts
> * Supports (plate adhesion)
> * 0.1mm resolution
> * 20% Infill
> * Tough PLA Black
> * Printing with Ultimaker 3 Extended

emmm... Ultimaker 3 Extended seems really good in resolution, if it can keep 0.1mm resolution I think it would be ok.

**Comment by AntoineTurmel** [comment]
Thanks, it's currently printing :)
I want to be sure that Pi0/PiSugar fits well, because I'll make a custom case based on it.

**Comment by AntoineTurmel** [comment]
Is it normal that the pisugar_case_button is at the same level of the case shell ?
It should stand out a little bit outside for the user to be able to push it.
I'm trying a modified version of it with a bigger size.

**Comment by AntoineTurmel** [comment]
Here is a photo of the case printed with a bigger button:
![IMG_20191108_161556](https://user-images.githubusercontent.com/119288/68491296-dace2580-024a-11ea-92f2-72f1cf20cac6.jpg)
![button](https://user-images.githubusercontent.com/119288/68491370-05b87980-024b-11ea-80f4-785e6856f063.png)

Here is the STL file modified:
[pisugar_case_button_bigger.zip](https://github.com/PiSugar/PiSugar/files/3825357/pisugar_case_button_bigger.zip)

I have yet to try it with the board inside, but I'm confident 😉

**Comment by AntoineTurmel** [comment]
So I finally assembled my case at home, it's working well but there is a bit of looseness.
(pisugar_case_thin_shell.stl file)

Here are some pictures:
![IMG_20191109_012032](https://user-images.githubusercontent.com/119288/68519241-222ad500-0290-11ea-94ec-9a003035d4f2.jpg)
![IMG_20191109_012054](https://user-images.githubusercontent.com/119288/68519242-222ad500-0290-11ea-9ec2-b10c7e3811e0.jpg)
![IMG_20191109_012143](https://user-images.githubusercontent.com/119288/68519244-222ad500-0290-11ea-836b-d4c4e67a186a.jpg)

It looks a bit dirty, I have to redo the cover but I'm quite happy for now 😄

**Comment by JdaieLin** [comment]
Nice work! =_<






------------------ Original ------------------

**Comment by snarflakes** [comment]
For these 3d printed cases, do the metal pi ports come through the printed material? Or lie just inside of the printed material? Thanks
