### ISSUE TITLE
Installation Issue when configuring pisugar-server

### ISSUE THREAD

**Issue by ben8622** [PiSugar/PiSugar#71]
When I am trying to install the software it eventually asks you to choose the PiSugar model in an interface similar to `sudo raspi-config`. When it reaches here I am unable to move up and down the selections using arrow keys which also stops me from hitting `<Ok>` and exiting the process. Hitting the arrow keys looks like the picture attached

Using a Raspberry Pi 4 with official Kali Linux for Raspberry Pi distribution. I can do `sudo raspi-config` and move the interface as normal. I have tried two different keyboards with the same results.
![image](https://user-images.githubusercontent.com/60989905/152225969-2f63d1ae-4c2b-4e78-b49e-7ac6d73cbcdf.png)

**Comment by JdaieLin** [comment]
@fengyc

**Comment by Logsleeve** [comment]
Did you ever get this figured out? I ran "sudo dpkg-reconfigure pisugar-server" and was able to select all of the prompts. However I never got the server to work on Kali. I also cannot update the firmware since its not for arm64. Did you ever get it running with Kali?

**Comment by ben8622** [comment]
Nope lol, it wasn't that important for the project I was using so I just left it

**Comment by mmider** [comment]
I have the same issue on my Pi Zero W running headless Debian Bookworm (am connected via ssh).

**Comment by mmider** [comment]
> I have the same issue on my Pi Zero W running headless Debian Bookworm (am connected via ssh).

The issue I've been experiencing on a fresh install of Debian Bookworm appears to have resolved itself after updating the system (`sudo apt-get upgrade`).
