### ISSUE TITLE
Charging slows down after reaching ~50%

### ISSUE THREAD

**Issue by nachotisnes** [PiSugar/PiSugar#73]
Hi!

I'm charging my PiSugar using a QI charger. The charging process works as expected: goes up to 100% and then drops to 80% (as set in my configuration), then goes up to 100% again.

I found that when charging from a nearly empty battery the level goes up very quickly at first and then slows down significantly (it takes maybe 3 or 4 times more to get from 50% to 100% than from 10% to 50%).

Is it like this by design? I've seen that some chargers slow down the process to protect the battery, and I don't know if this behaviour is a result of a design decision or problems in my QI setup.

thanks!

**Comment by JdaieLin** [comment]
Hi @nachotisnes,

the batter level is depended on the BAT voltage, which will goes up quickly at first at the beginning of charging. It's not by designed. It's a technical challenge to distinguish the battery output voltage and the charging voltage.
