### ISSUE TITLE
PiSugar 2 API problems

### ISSUE THREAD

**Issue by Mygglo** [PiSugar/PiSugar#74]
Hi !
I got some problems with the API.

echo "get battery" | nc -q 0 /tmp/pisugar-server.sock  = nc: missing port number

echo "get battery" | nc -U -q 0 127.0.0.1 8423 = nc: cannot use port with -U

echo "get battery" | nc  -q 0 127.0.0.1 8423 = Works and gives  "battery: 80.74887"

Thanks
mygglo

**Comment by JdaieLin** [comment]
hi, -U means the unix domain socket path. It should be:
echo "get battery" | nc -U /tmp/pisugar-server.sock -q 0
More detail please check this site: https://www.computerhope.com/unix/nc.htm
