### ISSUE TITLE
i2c not detected, PiSugar 3

### ISSUE THREAD

**Issue by bgilreath** [PiSugar/PiSugar#77]
sudo i2cdetect -y 1 shows no devices on bus 1. PiSugar3 Plus is providing power to pi.

**Comment by JdaieLin** [comment]
@wlmh110

**Comment by jpkong** [comment]
Hi, guys.

I met the same issue also.
When I gave the cmd 'sudo i2cdetect -y 1' to RPi 4B with PiSuagr3+, it puts the below.
(I'm currently using Ubuntu 21.04 desktop for RPi)
`
rpi@rpi-desktop:~$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
rpi@rpi-desktop:~$ 
`

Could anyone check on this?

**Comment by wlmh110** [comment]
> sudo i2cdetect -y 1 shows no devices on bus 1. PiSugar3 Plus is providing power to pi.

Hi，what system is used?

**Comment by wlmh110** [comment]
> Hi, guys.
> 
> I met the same issue also. When I gave the cmd 'sudo i2cdetect -y 1' to RPi 4B with PiSuagr3+, it puts the below. (I'm currently using Ubuntu 21.04 desktop for RPi)
> 
> ```
> rpi@rpi-desktop:~$ sudo i2cdetect -y 1
>      0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
> 00:                         -- -- -- -- -- -- -- -- 
> 10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
> 20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
> 30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
> 40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
> 50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
> 60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
> 70: -- -- -- -- -- -- -- --                         
> rpi@rpi-desktop:~$ 
> ```
> 
> Could anyone check on this?

Under Ubuntu system, bus1 may not be available, and bus0 may be available. Please try:
i2cdetect -y 0

**Comment by jpkong** [comment]
Hi, I checked it was an Ubuntu Desktop 21.04 version issue.
I don't know if the original OS image has the case or if some configs were wrong.
(I got the image from another engineer)

**Comment by wlmh110** [comment]
> Hi, I checked it was an Ubuntu Desktop 21.04 version issue. I don't know if the original OS image has the case or if some configs were wrong. (I got the image from another engineer) So, I'm considering using Ubuntu 20.04 or 22.04. 22.04 is OK.

It should be that different systems lead to different I2C buses. Please try 0 bus or check the system information
i2cdetect -y 0

**Comment by jpkong** [comment]
> > Hi, I checked it was an Ubuntu Desktop 21.04 version issue. I don't know if the original OS image has the case or if some configs were wrong. (I got the image from another engineer) So, I'm considering using Ubuntu 20.04 or 22.04. 22.04 is OK.
> 
> It should be that different systems lead to different I2C buses. Please try 0 bus or check the system information i2cdetect -y 0

I tried to use 'i2cdetect -y 0' in the 21.04, but there was no 0 I2C bus.
Anyway, I'm going to 22.04 or 20.04.

**Comment by Leviathan3DPrinting** [comment]
Also not showing up raspbian minimal

**Comment by Maynardnaze** [comment]
Thank god for amazon.. mine did the same thing. no response from buttons, just power on instantly with no I2C value.
