### ISSUE TITLE
PiSugar 2 Case files has the model 1 as depedency

### ISSUE THREAD

**Issue by fliodhais** [PiSugar/PiSugar#78]
Hi guys,

I am using Fusion 360 / autodesk viewer to import the PiSugar 2 Case and found that /model2/comp2.SLDASM fails to create the assembly due to a missing dependency: E:\github\PiSugar\model\pisugar_case_common_cap.SLDPRT.

I'd like to suggest copying pisugar_case_common_cap.SLDPRT to the model2 folder as it seemed to solve my problem.

I was wondering if:
1) The team can upload the STEP files for better cross-CAD software compatibility
~~2) How to change the file path that the SLDASM points to without access to Solidworks.~~ 

Thanks.

Edit: spelling
Edit 2: suggested solution

**Comment by JdaieLin** [comment]
Thanks for the suggestion, we will consider providing the step files.
