### ISSUE TITLE
PiSugar 3 Plus Extension Interface

### ISSUE THREAD

**Issue by Aftermac** [PiSugar/PiSugar#81]
I am working on a project using a Raspberry Pi 400. Do you have a diagram for wiring the Extension Interface pins from the PiSugar 3 Plus to the GPIO header?

**Comment by JdaieLin** [comment]
PiSugar3 Interface 5Voutput/GND/SDAT/SSCL  --->  Pi GPIO  4/6/3/5

**Comment by Aftermac** [comment]
Thank you!
