### ISSUE TITLE
Pi sugar 3 rpo

### ISSUE THREAD

**Issue by coutud** [PiSugar/PiSugar#84]
hi 
i have recieved my batterie but when i charge it the grenn led are blinking one by one but i can't power the raspebbry pi4
i push the power button nothing, it was charge by usb c 

thanks

**Comment by JdaieLin** [comment]
Hi, pisugar 3 has mis-touch feature enabled by default. Please try click and hold the power button to turn it on.

**Comment by coutud** [comment]
thanks work fine 
could you tell me what is the fonction of the four green led

**Comment by JdaieLin** [comment]
click once: show the battery level
click and hold(when anti mis-touch enabled): indicate the  anti mis-touch process, light up one by one
charging: light up one by one to current battery level

**Comment by coutud** [comment]
thanks all clear now
