### ISSUE TITLE
Pisugar 2 Pro stops charging after  5 mins when running PI4

### ISSUE THREAD

**Issue by mdobres** [PiSugar/PiSugar#86]
I have a Pisugar2 Pro connected to a RPI4.
But if the RPI is in use with power to Pisugar input, charging stops after 5 mins.

5V usb power supplied to PiSugar USB charge port  (ie not RPI power port)

-Boot RPI4: everything OK for 5 mins
-Pi is running, Pisugar software shows charging and meter shows 1.8 amps draw on 5v Supply
-After 5 mins Pisugar stops charging and power draw drops to zero.  Pi keeps running on battery

If I shutdown, charging re-starts.

Tried same thing with official RPI4 power supply, same result.

How do I set it up so that Pi runs from power supply but battery also charges?

Regards

Max

**Comment by JdaieLin** [comment]
Hi mdobres, the charging might be stopped when the battery level is higher than the charging range. You can click the batter icon on the WebUI to check if there is a range setting. You can set it to 100% than the charging will never stop when there's power supply.
