### ISSUE TITLE
Pi Sugar hardware compatibility

### ISSUE THREAD

**Issue by fheslouin** [PiSugar/PiSugar#87]
With the current Raspberry Pi shortage I was wondering if the Pi Sugar 3 plus would be compatible with other SBC such as Orange Pi for instance ?

**Comment by JdaieLin** [comment]
Hi  [fheslouin](https://github.com/fheslouin), we didn't test it on other boards. It should be ok if the GPIO is compatible. But there might be some differences on driver or i2c bus index, etc.
