### ISSUE TITLE
How do I know if I have PiSugar 2 (4-LEDs) or PiSugar 2 (2-LEDs)

### ISSUE THREAD

**Issue by wavesailor** [PiSugar/PiSugar#89]
Hi ... A few questions:

1. How do I know if I have PiSugar 2 (4-LEDs) or PiSugar 2 (2-LEDs)?

2. Do I just pull off those orange stickers covering the 4 mounting holes, so that I can attach my PiZero 2W with those included screws?

**Comment by JdaieLin** [comment]
1. PiSugar 2 (4-LEDs) is a very early version of PiSugar2, 4 leds are used for indicating power level. PiSugar 2 (2-LEDs) only have 2 led indicating full status / charging status.

2. Yes. Just pull off the orange stickers before you start using.
