### ISSUE TITLE
RF Noise When Off?

### ISSUE THREAD

**Issue by drewcovi** [PiSugar/PiSugar#9]
Is there some sort of capacitor getting used when the battery is "off"?

When my PiSugar turns off, I'm getting some RF noise from my RaspiAudio Mic+Speaker Hat, despite the Pi Zero being off. My only conclusion is somehow electrical signals are making their way through the GPIO pins.

Thanks!

**Comment by JdaieLin** [comment]
There is a little current for detecting power load when PiSugar is 'off'. The PiSugar will go off based on the detection when the pi shuts down. The current will not boot the pi but might still go through your pihat. It depends on the circus design of the phat.
