### ISSUE TITLE
model3: case cover cap *.STL missing 

### ISSUE THREAD

**Issue by Arthur-Philip-Dent** [PiSugar/PiSugar#92]
Hi *! 

Just wanted to ask, if it is possible to add a STL-File for case cover.
It's a bit tricky to convert *.SLDPRT or *.SLDDRW if you don't have the right tools.

I want to print a robust case for the Pi0-2W on PiSugar3 and wasnt able to find a *.STL file for the cap.

Thank you for that great work and your support! 
Best Regards!

**Comment by JdaieLin** [comment]
You can use this file: https://github.com/PiSugar/PiSugar/blob/master/model/pisugar_case_common_cap.STL
It's compatible with PiSugar 1~3 shell.

**Comment by Arthur-Philip-Dent** [comment]
Perfect! 
I wasn't prepared for such an easy solution!
