### ISSUE TITLE
PISugar3 Case issues

### ISSUE THREAD

**Issue by TomDII** [PiSugar/PiSugar#94]
Wanted to mention that the PISugar3 case files for download  have issues. 
#1 The 4 charging lights are on the same side as the switches now.  Case it's on the end. 
#2 The power button does not have the recessed space like the other button so when you assemble the case the power button is pushed down.

**Comment by JdaieLin** [comment]
Thanks for the feedback. I had fixed them in the latest commit.

**Comment by TomDII** [comment]
Thanks, printed and worked perfect.  Buttons are a little sloppy, I scaled them up .5mm x and y. And fits perfect. 112.5% and 105% if anyone wants to try.
