### ISSUE TITLE
Cant upgrade firmware 

### ISSUE THREAD

**Issue by T-REX-XP** [PiSugar/PiSugar#95]
**SBC:** radxa zero
**OS:** dietpi
**Command:** `curl https://cdn.pisugar.com/release/PiSugarUpdate.sh | sudo bash`
**Error:**
![image](https://user-images.githubusercontent.com/4560084/187027025-8d6f1afd-06eb-4a2c-a886-c069ad682349.png)

**Comment by JdaieLin** [comment]
@fengyc
