### ISSUE TITLE
pisugar pro 3

### ISSUE THREAD

**Issue by coutud** [PiSugar/PiSugar#97]
Hi
I have a sugar pro 3 but when i push the power button the sugar doesn't power on i think it's due to secure button how i can solve my problem

thanks

**Comment by Ra2-IFV** [comment]
Click the power button, hold it when you see lights are up, then you your Pi Sugar 3 should be on.
You can disable this feature in WebUI
[Wiki here](https://github.com/PiSugar/PiSugar/wiki/PiSugar-3-Series#%EF%B8%8F-anti-mistaken-touch-switch)
